"use client";

import type { CollectionInspection, VariableSource } from "@/lib/api";
import { missingValues, variablesToAsk } from "@/lib/executionJob";

const SOURCE_TEXT: Record<VariableSource, string> = {
  supplied: "supplied by you",
  environment: "from the environment file",
  collection: "from the collection variables",
  dynamic: "Postman built-in, generated by Newman",
  script: "set at runtime by a script in the collection",
  unresolved: "missing",
};

/** Step 2: supply every unresolved variable. Secret-looking names are password
 * inputs; values stay in memory only and are cleared once the job is created. */
export function VariablesStep({
  inspection,
  values,
  onChange,
  onBack,
  onContinue,
}: {
  inspection: CollectionInspection;
  values: Record<string, string>;
  onChange: (values: Record<string, string>) => void;
  onBack: () => void;
  onContinue: () => void;
}) {
  const asked = variablesToAsk(inspection);
  const askedNames = new Set(asked.map((v) => v.name));
  const others = inspection.variables.filter((v) => !askedNames.has(v.name));
  const missing = missingValues(asked.map((v) => v.name), values);

  return (
    <div className="card space-y-5 p-6">
      <div>
        <h2 className="text-lg font-semibold">Variables</h2>
        <p className="mt-1 text-sm text-slate-400">
          Values are never replaced with empty strings — every variable the collection uses must come from
          somewhere before it can run.
        </p>
      </div>

      {asked.length === 0 ? (
        <p className="rounded bg-ok/10 px-3 py-2 text-sm text-ok">No values needed — every variable is resolved.</p>
      ) : (
        <div className="space-y-3">
          <h3 className="text-sm font-medium">Values to supply ({asked.length})</h3>
          {asked.map((v) => (
            <div key={v.name}>
              <div className="flex items-center gap-2">
                <label htmlFor={`var-${v.name}`} className="mono text-sm">
                  {v.name}
                </label>
                {v.sensitive && <span className="badge badge-medium">secret · hidden</span>}
              </div>
              <input
                id={`var-${v.name}`}
                type={v.sensitive ? "password" : "text"}
                autoComplete={v.sensitive ? "new-password" : "off"}
                spellCheck={false}
                value={values[v.name] ?? ""}
                onChange={(e) => onChange({ ...values, [v.name]: e.target.value })}
                className="mono mt-1 w-full rounded-md border border-edge bg-ink/60 px-3 py-2 text-sm focus:border-brand focus:outline-none"
              />
              <p className="mt-0.5 text-xs text-slate-500">Used in {v.locations.slice(0, 3).join(", ")}{v.locations.length > 3 ? " …" : ""}</p>
            </div>
          ))}
        </div>
      )}

      {others.length > 0 && (
        <div>
          <h3 className="text-sm font-medium">Already resolved ({others.length})</h3>
          <ul className="mt-2 space-y-1 text-sm">
            {others.map((v) => (
              <li key={v.name} className="flex flex-wrap items-center justify-between gap-2 rounded bg-ink/50 px-3 py-1.5">
                <span className="mono">{v.name}</span>
                <span className="text-xs text-slate-400">{SOURCE_TEXT[v.source]}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="flex justify-between gap-2">
        <button className="btn-ghost" onClick={onBack}>
          Back
        </button>
        <button className="btn" disabled={missing.length > 0} onClick={onContinue}>
          Continue
        </button>
      </div>
      {missing.length > 0 && asked.length > 0 && (
        <p className="text-right text-xs text-slate-500">Still needed: {missing.join(", ")}</p>
      )}
    </div>
  );
}
