"""Spec §11: reports generated by an execution job produce the same analysis as
uploading those same reports directly (the job adds no transformation)."""

import json

from fastapi.testclient import TestClient

from app.api.deps import get_job_dispatcher, get_newman_runner
from app.domain.execution_job import RunOutcome
from app.main import create_app
from app.services.fake_newman_runner import FakeNewmanRunner
from app.services.job_dispatcher import InlineJobDispatcher
from tests.fixtures import builders as b
from tests.fixtures.postman_builders import pm_collection, pm_request


def _report(token: str, order: str) -> bytes:
    return json.dumps(b.report("Parity", [
        b.execution("Login", "POST", "https://api.example.com/login", resp_body={"token": token}, position=0),
        b.execution("Create", "POST", "https://api.example.com/orders",
                    req_headers=[b.header("Authorization", f"Bearer {token}")],
                    resp_body={"orderId": order}, position=1),
        b.execution("Get", "GET", f"https://api.example.com/orders/{order}",
                    req_headers=[b.header("Authorization", f"Bearer {token}")], position=2),
    ])).encode()


_BASELINE = _report("tok_A1b2C3d4E5", "ORD-7731aa")
_COMPARISON = _report("tok_Z9y8X7w6V5", "ORD-1842bb")

_COMPARED = ("mode", "candidate_count", "insight_count", "summary", "readiness", "blocked", "alignment")


def test_job_analysis_equals_direct_upload_analysis():
    app = create_app()
    runner = FakeNewmanRunner([RunOutcome(True, _BASELINE), RunOutcome(True, _COMPARISON)])
    app.dependency_overrides[get_newman_runner] = lambda: runner
    app.dependency_overrides[get_job_dispatcher] = InlineJobDispatcher
    client = TestClient(app)

    collection = pm_collection("Parity", [pm_request("Login", "POST", "https://93.184.216.34/login")])
    job = client.post("/api/v1/execution-jobs", data={"confirm": "true", "supplied_values_json": "{}"},
                      files={"collection": ("c.json", json.dumps(collection).encode(), "application/json")}).json()
    status = client.get(f"/api/v1/execution-jobs/{job['job_id']}").json()
    assert status["state"] == "ready", status
    via_job = client.get(f"/api/v1/analyses/{status['analysis_id']}").json()

    uploaded = client.post("/api/v1/analyses", files=[
        ("files", ("baseline.json", _BASELINE, "application/json")),
        ("files", ("comparison.json", _COMPARISON, "application/json")),
    ])
    assert uploaded.status_code == 201, uploaded.text
    via_upload = uploaded.json()

    assert via_job["candidate_count"] >= 1
    for key in _COMPARED:
        assert via_job[key] == via_upload[key], key
    job_cands = client.get(f"/api/v1/analyses/{via_job['analysis_id']}/candidates").json()["items"]
    upload_cands = client.get(f"/api/v1/analyses/{via_upload['analysis_id']}/candidates").json()["items"]
    assert sorted(c["variable_name"] for c in job_cands) == sorted(c["variable_name"] for c in upload_cands)
