import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { expect, test } from "@playwright/test";

// Explicit opt-in: this creates, updates and deletes bookings on a public demo API.
test.skip(process.env.E2E_LIVE_BOOKING !== "1", "Set E2E_LIVE_BOOKING=1 to exercise the public booking API");

test("public booking collection through browser to JMeter", async ({ page }) => {
  const root = path.resolve(__dirname, "../..");
  const out = path.join(root, ".smoke/browser-booking");
  mkdirSync(out, { recursive: true });
  const evidence: Record<string, unknown> = { testedAt: new Date().toISOString() };
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByLabel("Collection file").setInputFiles(path.join(root, "samples/booking-flow.postman_collection.json"));
  await page.getByLabel("Environment file").setInputFiles(path.join(root, "samples/booking-flow.postman_environment.json"));
  await page.screenshot({ path: path.join(out, "01-upload.png"), fullPage: true });
  const inspected = page.waitForResponse(r => r.url().endsWith("/execution-jobs/inspect") && r.request().method() === "POST");
  await page.getByRole("button", { name: /inspect collection/i }).click();
  const inspection = await (await inspected).json();
  evidence.inspection = inspection;
  console.log("INSPECT", JSON.stringify(inspection));
  await page.getByRole("button", { name: /continue/i }).click();
  await page.screenshot({ path: path.join(out, "02-review.png"), fullPage: true });
  await page.getByRole("button", { name: /run collection twice/i }).click();
  await expect(page.getByRole("tab", { name: "Run health" })).toBeVisible({ timeout: 240_000 });
  await page.screenshot({ path: path.join(out, "03-run-health.png"), fullPage: true });
  evidence.healthText = await page.locator("main").innerText();
  console.log("HEALTH", evidence.healthText);
  await page.getByRole("tab", { name: /^Candidates/ }).click();
  const correlated = page.waitForResponse(r => r.url().endsWith("/auto-correlate") && r.request().method() === "POST");
  await page.getByRole("button", { name: /auto-correlate all reused values/i }).click();
  const correlations = await (await correlated).json();
  evidence.correlations = { total: correlations.total, variables: correlations.variables };
  console.log("CORRELATIONS", JSON.stringify(evidence.correlations));
  await expect(page.getByText(/correlation completed/i).first()).toBeVisible();
  await page.screenshot({ path: path.join(out, "04-correlations.png"), fullPage: true });
  await page.getByRole("tab", { name: /^Generate/ }).click();
  await page.getByRole("button", { name: "Generate JMX" }).click();
  await expect(page.getByRole("button", { name: "Download Generated JMX" })).toBeVisible();
  const password = page.getByPlaceholder("value for -Jpassword");
  await password.fill("password123");
  const validated = page.waitForResponse(r => r.url().endsWith("/validate") && r.request().method() === "POST", { timeout: 240_000 });
  await page.getByRole("button", { name: "Validate with JMeter" }).click();
  evidence.validation = await (await validated).json();
  console.log("VALIDATION", JSON.stringify(evidence.validation));
  writeFileSync(path.join(out, "evidence.json"), JSON.stringify({ ...evidence, browserErrors: errors }, null, 2));
  await page.screenshot({ path: path.join(out, "05-jmeter-validation.png"), fullPage: true });
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download Generated JMX" }).click();
  const download = await downloadPromise;
  await download.saveAs(path.join(out, download.suggestedFilename()));
  const jmx = readFileSync(await download.path(), "utf8");
  expect(jmx).not.toContain("password123");
  expect(jmx).toContain("JSONPostProcessor");
  expect(jmx).toContain("${bookingid}");
  expect(jmx).toContain("vars.get('token')");
  const manifestDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download manifest" }).click();
  const manifest = await manifestDownload;
  await manifest.saveAs(path.join(out, manifest.suggestedFilename()));
  expect((evidence.validation as any).status).toBe("validated");
  expect((evidence.validation as any).report.samplers_total).toBe(7);
  expect((evidence.validation as any).report.samplers_failed).toBe(0);
  expect(errors).toEqual([]);
});
